### ISSUE TITLE
Need to improve register_setting option

### ISSUE THREAD

**Issue by ppprakhar** [OlegApanovich/import-products-from-gsheet-for-woo-importer#10]
under menu woocommerce , I have replace function for save setting with this

register_setting(
			'plugin_wc_import_google_sheet_options',
			'plugin_wc_import_google_sheet_options',
			['sanitize_callback' => array( $this, 'set_options' )]
		);

**Comment by OlegApanovich** [comment]
Thank you for your help. I try to implement it in commit 03af3326d1719c037823e0fc3323f98576693c27 If you find a time to review it or create pull request to improve it will be highly appreciated
