### ISSUE TITLE
Fatal Error with WP 5.7.1

### ISSUE THREAD

**Issue by monica123m** [OlegApanovich/import-products-from-gsheet-for-woo-importer#12]
Impossible to start an import. It says its malformed, but it worked until few hours ago. Anyway, i use the standard woocommerce scheme so it can't be malformed, imho. 

here's the sheet: https://docs.google.com/spreadsheets/d/1t0QeRRtVkqlcrZphsUJadv9yJ0lQJdqI_iQVfDcH8I8/edit?usp=sharing

Here's the screen error:
Fatal error: Uncaught Google\Spreadsheet\Exception\BadRequestException: <html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"><title>Error 400 (Bad Request)!!1</title><style nonce="k8pt/JOMwa7w3+VwjGa1jw">*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{color:#222;text-align:unset;margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px;}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}pre{white-space:pre-wrap;}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><div id="af-error-container"><a href=//www.google.com><span id=logo aria-label=Google></span></a><p><b>400.</b> <ins>That’s an error.</ins><p>The server cannot process the request because it is malformed. It should not be retried. <ins>That’s all we know.</ins></div> in /home/femarofa/public_html/farmacia/wp-content/plugins/import-products-from-gsheet-for-woo-importer/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/DefaultServiceRequest.php:359 Stack trace: #0 /home/femarofa/public_html/farmacia/wp-content/plugins/import-products-from-gsheet-for-woo-importer/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/DefaultServiceRequest.php(241): Google\Spreadsheet\DefaultServiceRequest->execute(Object(CurlHandle)) #1 /home/femarofa/public_html/farmacia/wp-content/plugins/import-products-from-gsheet-for-woo-importer/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/Worksheet.php(168): Google\Spreadsheet\DefaultServiceRequest->get('https://docs.go...') #2 /home/femarofa/public_html/farmacia/wp-content/plugins/import-products-from-gsheet-for-woo-importer/includes/class-gswoo-wrapper-api-google-drive.php(118): Google\Spreadsheet\Worksheet->getCsv() #3 /home/femarofa/public_html/farmacia/wp-content/plugins/import-products-from-gsheet-for-woo-importer/woocommerce-importer/class-gswoo-wc-product-csv-importer-controller.php(172): GSWOO_Wrapper_Api_Google_Drive->get_sheet_csv() #4 /home/femarofa/public_html/farmacia/wp-content/plugins/import-products-from-gsheet-for-woo-importer/woocommerce-importer/class-gswoo-wc-product-csv-importer-controller.php(75): GSWOO_WC_Product_CSV_Importer_Controller->google_sheet_get_csv_file('AGGIORNA PRODOT...') #5 /home/femarofa/public_html/farmacia/wp-content/plugins/woocommerce/includes/admin/importers/class-wc-product-csv-importer-controller.php(294): GSWOO_WC_Product_CSV_Importer_Controller->handle_upload() #6 /home/femarofa/public_html/farmacia/wp-content/plugins/woocommerce/includes/admin/importers/class-wc-product-csv-importer-controller.php(268): WC_Product_CSV_Importer_Controller->upload_form_handler(Object(GSWOO_WC_Product_CSV_Importer_Controller)) #7 /home/femarofa/public_html/farmacia/wp-content/plugins/import-products-from-gsheet-for-woo-importer/woocommerce-importer/class-gswoo-wc-admin-importers.php(56): WC_Product_CSV_Importer_Controller->dispatch() #8 /home/femarofa/public_html/farmacia/wp-includes/class-wp-hook.php(292): GSWOO_WC_Admin_Importers->product_importer('') #9 /home/femarofa/public_html/farmacia/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array) #10 /home/femarofa/public_html/farmacia/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #11 /home/femarofa/public_html/farmacia/wp-admin/admin.php(259): do_action('product_page_pr...') #12 /home/femarofa/public_html/farmacia/wp-admin/edit.php(10): require_once('/home/femarofa/...') #13 {main} thrown in /home/femarofa/public_html/farmacia/wp-content/plugins/import-products-from-gsheet-for-woo-importer/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/DefaultServiceRequest.php on line 359

**Comment by OlegApanovich** [comment]
Desperately try reproduce your issue with your sheet: https://docs.google.com/spreadsheets/d/1t0QeRRtVkqlcrZphsUJadv9yJ0lQJdqI_iQVfDcH8I8/edit?usp=sharing and my local enviroment
Worpdress 5.7.1
Woocommerce 5.2.2
PHP 8.0
But no luck, import run good in it without any errors.
It will be helpful if you can provide access to your environment and I try to figure it out there.

**Comment by monica123m** [comment]
Thank you very much for your time and effort!
Give me few more days, i'll finish to import by csv my remaining products then l'ill give you access to my backend, using an updated version of the shared file to test if everythings works.

Thanks again

**Comment by monica123m** [comment]
Hi Oleg, i was trying right now the plugin hoping to import last products and, i don't know how, now it works fine. I think it was a sync error or a php error, but in any case related to my web server.  Thank you very much for your effort! I am sorry for wasted your time. 
Have a great day
