### ISSUE TITLE
the plugin stopped working

### ISSUE THREAD

**Issue by freddyjcm** [OlegApanovich/import-products-from-gsheet-for-woo-importer#18]
apparently the connection that was being used to access google has changed and no longer allows you to connect

**Comment by leolamanna** [comment]
It never worked again. All the reference resources provided for the "Manual Connect" option are outdated and useless for someone unfamiliar with Google APIs. Unfortunately, an exceptional work that has become useless from one day to the next (it has been around a month now, without working and with no solution in sight)   =(

**Comment by OlegApanovich** [comment]
Google changed rules https://github.com/OlegApanovich/import-products-from-gsheet-for-woo-importer/issues/19#issuecomment-1331658736 for connection to his API with for 'One Click Auto Connect Method' https://i.imgur.com/tnWOU62.png It needs time to implement it again. But I checked and the second connection method 'Manual Connect' is working https://i.imgur.com/hudYEdb.png , maybe doc is outdated but you can find some actual info about the connection on google's side. I will try to fix it asap. More info about when I can do it I provided here https://github.com/OlegApanovich/import-products-from-gsheet-for-woo-importer/issues/19#issuecomment-1331658736

**Comment by OlegApanovich** [comment]
@freddyjcm  we fixed 'One Click Auto Connect' method. Please update your plugin to the latest 2.3 version.
