### ISSUE TITLE
PROJECT ABANDONED?

### ISSUE THREAD

**Issue by leolamanna** [OlegApanovich/import-products-from-gsheet-for-woo-importer#19]
Not working anymore (has been dead for more than a month) by the "One click auto connect" option...  and all the referenced resources provided here for the "Manual Connect" option are outdated and useless for someone unfamiliar with Google APIs.  =(

**Comment by OlegApanovich** [comment]
Sorry for everyone it is a pet no-profit project that I develop on my own. Right now I am in Ukraine and there is a war here, we have electricity and internet shortages here, so there is no way for me right now to develop it. I will return to it asap if something changes on the good side.

**Comment by leolamanna** [comment]
I'm sorry about it. Not wanting to bother in such circumstances. I hope it all ends soon and for good. FORCE UKRAINE!

**Comment by OlegApanovich** [comment]
@leolamanna we fixed 'One Click Auto Connect' method. Please update your plugin to the latest 2.3 version.

**Comment by leolamanna** [comment]
> @leolamanna we fixed 'One Click Auto Connect' method. Please update your plugin to the latest 2.3 version.

Thank you very much! =)
