### ISSUE TITLE
Intagrate multiple google sheet optionality

### ISSUE THREAD

**Issue by OlegApanovich** [OlegApanovich/import-products-from-gsheet-for-woo-importer#4]
Right now we can import only from one google sheet, it will be greate if user has option to choose between google sheet that stored on his google drive. In import page we already have select field for it but only with one google sheet that predefind in plugin option page.
For realisition we need to get all google sheets that connecteted  google drive has and load all of them titles to existing select field. After it we can remove google sheet title option from plugin option page.

**Comment by fedts** [comment]
It would be very useful. Would it be possible just by adding multiple gsheet name in the field separated by comme?

**Comment by OlegApanovich** [comment]
Right now there is implementation of it only in multipleGsheet branch

**Comment by KoolPal** [comment]
> Right now there is implementation of it only in multipleGsheet branch

Hi @OlegApanovich : Can you please help me in understanding HOW to use this multipleGsheet branch?? Thanks a lot

**Comment by OlegApanovich** [comment]
Hi @KoolPal after google updated his API so ver 4 https://github.com/OlegApanovich/import-products-from-gsheet-for-woo-importer/issues/15 we have an emergency update of our plugin and all old functionality do not supported anymore. I will drop these branch cos in the current realization we already have a more user-friendly dropdown select for the title field, for him we do not have multiple selections right now, maybe we implement it in the feature then I let you know about it in these thread. For now, the only option to switch between sheets is only on a settings page with an exiting dropdown if you connected with 'One Click Auto Connect' option https://i.imgur.com/T7rRJEa.png

**Comment by KoolPal** [comment]
@OlegApanovich Thank you very much for your detailed reply. I shall use the Sheet switching option as explained by you. 
Thanks again. Take care!
