### ISSUE TITLE
The importer is duplicating existing products after import

### ISSUE THREAD

**Issue by ChrisHinds57** [OlegApanovich/import-products-from-gsheet-for-woo-importer#7]
When the price is changed it is also duplicating the products insteadof updating them

**Comment by OlegApanovich** [comment]
Right now plugin do not importing any product itself. It just wrapper above standard woocommerce import functionality.
Please try to import products through standard woocommerce plugin if products duplicata again then report about issue on woocommerce issue plugin page  https://github.com/woocommerce/woocommerce/issues, if not please report me again.
